name: Terraform

on:
  pull_request:
    paths:
      - 'infra/modules/**'
      - '*/infra/financial_pipeline/**'

jobs:
  fmt-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform validate (dev)
        working-directory: dev/infra/financial_pipeline
        run: terraform init -backend=false && terraform validate

      - name: Terraform validate (staging)
        working-directory: staging/infra/financial_pipeline
        run: terraform init -backend=false && terraform validate

      - name: Terraform validate (prod)
        working-directory: prod/infra/financial_pipeline
        run: terraform init -backend=false && terraform validate
