name: Terraform CI

on:
  push:
    branches:
      - dev
      - staging
      - prod
  pull_request:
    branches:
      - dev
      - staging
      - prod

jobs:
  fmt-validate-plan:
    strategy:
      matrix:
        env: [dev, staging, prod]
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform fmt (check)
        working-directory: ${{ matrix.env }}/infra/financial_pipeline
        run: terraform fmt -check

      - name: Terraform init (no-backend)
        working-directory: ${{ matrix.env }}/infra/financial_pipeline
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: ${{ matrix.env }}/infra/financial_pipeline
        run: terraform validate

      - name: Terraform plan
        working-directory: ${{ matrix.env }}/infra/financial_pipeline
        run: terraform plan -out=tfplan

      - name: Upload tfplan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan-${{ matrix.env }}
          path: ${{ matrix.env }}/infra/financial_pipeline/tfplan

