name: Terraform CI

on:
  push:
    branches:
      - main
      - dev
      - staging
      - prod
  pull_request:
    branches:
      - main
      - dev
      - staging
      - prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, staging, prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform fmt
        working-directory: ${{ matrix.env }}/infra/financial_pipeline
        run: terraform fmt -check

      - name: Terraform init (no-backend)
        working-directory: ${{ matrix.env }}/infra/financial_pipeline
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: ${{ matrix.env }}/infra/financial_pipeline
        run: terraform validate

      - name: Terraform plan
        working-directory: ${{ matrix.env }}/infra/financial_pipeline
        run: terraform plan -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.env }}
          path: ${{ matrix.env }}/infra/financial_pipeline/tfplan
