name: Terraform CI

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init & Plan (dev)
        working-directory: dev/infra/financial_pipeline
        run: terraform init -reconfigure -backend-config="bucket=ross-data-pipeline-tfstate" -backend-config="key=dev/financial_pipeline/terraform.tfstate" -backend-config="region=us-east-1" -backend-config="dynamodb_table=ross-data-pipeline-tfstate-locks" && terraform plan -lock=false
      # You can duplicate the above for staging/prod with manual approvals
